const data = [  {
    name: "10921",
    desc: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. It has survived not only five centuries.",
    price: "2999",
    inSale: true,
    saleAmount: 0.1,
    rate: "5",
    imgSrc: "src/utils/images/pos1.svg",
  },
  {
    name: "10753",
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature.",
    price: "4120",
    inSale: false,
    saleAmount: 0.0,
    rate: "4.8",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "10545",
    desc: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    price: "2800",
    inSale: true,
    saleAmount: 0.2,
    rate: "4.2",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "10432",
    desc: "Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text.",
    price: "3750",
    inSale: true,
    saleAmount: 0.05,
    rate: "5",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "11023",
    desc: "Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humor and the like).",
    price: "4900",
    inSale: false,
    saleAmount: 0.0,
    rate: "3.9",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "10987",
    desc: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
    price: "3400",
    inSale: true,
    saleAmount: 0.25,
    rate: "4.7",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "10378",
    desc: "If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
    price: "3250",
    inSale: true,
    saleAmount: 0.1,
    rate: "4.3",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "10856",
    desc: "Lorem Ipsum is simply dummy text of the printing industry, but its origins date back to a piece of classical literature.",
    price: "2780",
    inSale: false,
    saleAmount: 0.0,
    rate: "4.0",
    imgSrc: "src/utils/images/pos2.svg",
  },
  {
    name: "11245",
    desc: "The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested.",
    price: "5050",
    inSale: true,
    saleAmount: 0.3,
    rate: "4.9",
    imgSrc: "src/utils/images/pos2.svg",
  },
];
export default data;
